name: "github-discord-widget-dev"

networks:
  db-network:
    driver: bridge

volumes:
  postgres-data:

services:
  bot:
    container_name: github-widget-bot
    build:
      context: .
      dockerfile: GitHubWidgetBot/Dockerfile
    restart: unless-stopped
    env_file:
      - ${BOT_ENV_FILE:-.env}
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
      Database__ConnectionString: "Host=postgres;Port=5432;Database=${POSTGRES_DB:-wdgt-db};Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-postgres}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - db-network

  postgres:
    container_name: postgres-db
    image: postgres:18.4-trixie
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-wdgt-db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - db-network
