// <auto-generated />
using System;
using GitHubWidgetBot.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GitHubWidgetBot.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260621180641_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("github_widget")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GitHubWidgetBot.Persistence.DTOs.RefreshTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_user_id");

                    b.Property<long>("FailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("failure_count");

                    b.Property<string>("GitHubUsername")
                        .IsRequired()
                        .HasMaxLength(39)
                        .HasColumnType("character varying(39)")
                        .HasColumnName("git_hub_username");

                    b.Property<DateTimeOffset>("LastAttemptUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_utc");

                    b.Property<DateTimeOffset>("LastUpdateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_utc");

                    b.HasKey("Id")
                        .HasName("pk_refresh_targets");

                    b.HasIndex("LastUpdateUtc")
                        .HasDatabaseName("ix_refresh_targets_last_update_utc");

                    b.HasIndex("DiscordUserId", "GitHubUsername")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_targets_discord_user_id_git_hub_username");

                    b.ToTable("refresh_targets", "github_widget");
                });

            modelBuilder.Entity("GitHubWidgetBot.Persistence.DTOs.SetupSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_user_id");

                    b.Property<string>("GitHubDeviceCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("git_hub_device_code");

                    b.Property<DateTimeOffset>("GitHubExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("git_hub_expires_at_utc");

                    b.Property<long>("GitHubPollIntervalSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("git_hub_poll_interval_seconds");

                    b.HasKey("Id")
                        .HasName("pk_setup_sessions");

                    b.HasIndex("DiscordUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_setup_sessions_discord_user_id");

                    b.HasIndex("GitHubExpiresAtUtc")
                        .HasDatabaseName("ix_setup_sessions_git_hub_expires_at_utc");

                    b.ToTable("setup_sessions", "github_widget");
                });
#pragma warning restore 612, 618
        }
    }
}
